### ISSUE TITLE
Backen-End Resource API

### ISSUE THREAD

**Issue by paullaster** [C-I-T-CLUB/CIT_CLUB_OFFICIAL_WEB_APP_-BACKEND#11]
Designing backend api resource api
@Stephen-Kamau

**Comment by Stephen-Kamau** [comment]
Hey, Did we decide on using Class based?

**Comment by paullaster** [comment]
Is it really necessary?

We didn't agree plus we can consider the next version.
RoboticaVision

**Comment by Stephen-Kamau** [comment]
Got it, Will use functional based views

**Comment by Stephen-Kamau** [comment]
What is RoboticaVision?

**Comment by Stephen-Kamau** [comment]
@paullaster  Regarding resources, Will they be open ended? like i mean i just include endpoints without auth since i'm not quite sure of how the two different users will interact?

**Comment by paullaster** [comment]
Hey! Sorry it was my sabbath.

**Comment by paullaster** [comment]
So have auth for all the resources

**Comment by Stephen-Kamau** [comment]
Hi, 
Update on the fields for the resources to be uploaded,

I have assumed that these resources are papers only and information for them is Uploader, Unit name, date, description.

Is their an important field am missing?  Send an update of these

**Comment by paullaster** [comment]
Hi too Steve,
Okay that can be okay for the MVP.
We'll consider other things after version one
RoboticaVision

**Comment by paullaster** [comment]
done
